### ISSUE TITLE
SSB!

### ISSUE THREAD

**Issue by M190200623** [CefasRepRes/LeMaRns#1]
library(LeMaRns)
NS_params <- LeMansParam(NS_par, tau=NS_tau, eta=NS_eta, L50=NS_L50,other=1e12)
#> Warning in .local(df, gdf, ...): The following columns of df do not match any of the species arguments and were therefore added to recruit_params:
#> a, b
effort <- matrix(0.25, 50, dim(NS_params @Qs)[3])
model_run <- run_LeMans(NS_params, years=50, effort=effort)
plot_SSB(NS_params,model_run)

Through the above code to run out of the diagram(SSB), in addition to checking the ecosystem to achieve balance, is there any other role? Can it be compared with the observed data?

**Comment by michaelspence** [comment]
`NS_params <- LeMansParam(NS_par, tau=NS_tau, eta=rep(0.25, 21), L50=NS_par$Lmat, other=1e12)`
`effort <- matrix(0.5, 10, dim(NS_params@Qs)[3])`
`model_run <- run_LeMans(NS_params, years=10, effort=effort)`
`SSB <- get_SSB(inputs=NS_params, outputs=model_run)`

`get_SSB` returns a matrix with dimensions `length(time_steps)` by `length(species)` where the `i`,`j`th element is the SSB (g) of the `j`th species in the `i`th `time_steps`. For more details see `help("get_SSB")` and `help("calc_SSB")`.

`calc_SSB` will show you the code for that function and `getMethod("get_SSB",c("missing","missing"))` to see the code for these calculations.

Also see:
https://github.com/CefasRepRes/LeMaRns/blob/master/R/get_SSB.R

**Comment by M190200623** [comment]
I know the code, I don't know the function of the graph obtained by plot_SSB! Just to check whether the ecosystem is in balance?
Thank you very much!

**Comment by michaelspence** [comment]
There could be many reasons to plot the SSB. This maybe what you were interested in if you were using `LeMaRns` to do some kind of assessment or projection of the system. We added this plot to the package as an option for the user. You can make your own plot, possibly using the `get_SSB` function, and then add the observations to that plot if you wanted.

**Comment by M190200623** [comment]
After 5000 iterations, I got the b value, but the SSB diagram did not reach the balance. What is the most important point affecting the balance and how to balance it.
Thank you very much!

**Comment by michaelspence** [comment]
I'm not really sure. After 5000 iterations of what? Any chance you can share your code?
